In [1]:
import pandas as pd
import requests
import numpy as np
import seaborn as sns
sns.set_style('darkgrid')
import matplotlib.pyplot as plt
import sklearn

In [2]:
loans=pd.read_csv('lending_club_new_data.csv')
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_late_fee  \
0  27.65            0               1         3  ...                0.00   
1   1.00            0               5         3  ...                0.00   
2   8.72            0               2         2  ...                0.00   
3  20.00            0               1        10  ...               16.97   
4  11.20            0               3         9  ...                0.00   

   recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
0        0.00                     0.00           171.62          0   
1      117.08                     1.11           119.66          1   
2        0.00                     0.00           649.91          0   
3        0.00                     0.00           357.48          0   
4        0.00                     0.00           161.03          0   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 24 columns]

In [3]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516 entries, 0 to 9515
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   loan_amnt                9516 non-null   int64  
 1   funded_amnt              9516 non-null   int64  
 2   funded_amnt_inv          9516 non-null   int64  
 3   int_rate                 9516 non-null   float64
 4   installment              9516 non-null   float64
 5   annual_inc               9516 non-null   int64  
 6   dti                      9516 non-null   float64
 7   delinq_2yrs              9516 non-null   int64  
 8   inq_last_6mths           9516 non-null   int64  
 9   open_acc                 9516 non-null   int64  
 10  total_pymnt              9516 non-null   float64
 11  total_pymnt_inv          9516 non-null   float64
 12  total_rec_prncp          9516 non-null   float64
 13  total_rec_int            9516 non-null   float64
 14  total_rec_late_fee      

In [4]:
loans['good_loans']=loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [5]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [6]:
loans.tail()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
9511       6000         6000             6000     23.40       170.53   
9512      15250        15250            15250     17.57       548.05   
9513       8525         8525             8525     18.25       217.65   
9514      22000        22000            22000     19.97       582.50   
9515       2000         2000             2000      7.90        62.59   

      annual_inc    dti  delinq_2yrs  inq_last_6mths  open_acc  ...  \
9511       45600   1.50            1               0         3  ...   
9512       65000  11.26            1               2         8  ...   
9513       37536  12.28            4               0        12  ...   
9514       78000  18.45            0               5        18  ...   
9515       83000   5.39            3               1        21  ...   

      recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
9511         0.0                    0.000           170.53          1   
9512         0.0                    0.000         14810.30          0   
9513      1159.4                   11.594           217.65          1   
9514         0.0                    0.000            17.50          1   
9515         0.0                    0.000          1500.68          0   

      emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
9511               0          2            1.0                 0   
9512              11          3            0.4                 0   
9513               6          3            0.6                 0   
9514              11          3            1.0                 1   
9515               4          6            0.8                 0   

      payment_inc_ratio  good_loans  
9511           4.487630          no  
9512          10.117800         yes  
9513           6.958120          no  
9514           8.961540          no  
9515           0.904916         yes  

[5 rows x 25 columns]

In [7]:
x =loans.drop(['good_loans','bad_loans'],axis = 1)
y = loans['good_loans']

In [8]:
print(x.shape,y.shape)

(9516, 23) (9516,)


In [9]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=124)

In [10]:
print(x_train.shape,y_train.shape)

(6661, 23) (6661,)


In [11]:
print(x_test.shape,y_test.shape)

(2855, 23) (2855,)


### Decision Tree 

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model2 = DecisionTreeClassifier()

In [14]:
model2.fit(x_train,y_train) 

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [15]:
prediction = model2.predict(x_test) 

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
print (confusion_matrix (y_test, prediction))

[[ 443   12]
 [   7 2393]]


In [18]:
# finally we conclued that 444 and 2393  prediction are true
#                           11  and  7 prediction are falls

In [19]:
print (classification_report (y_test, prediction))

              precision    recall  f1-score   support

          no       0.98      0.97      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.99      0.99      2855
weighted avg       0.99      0.99      0.99      2855



### Random Forests

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf_model2 = RandomForestClassifier(n_estimators = 150)

In [22]:
rf_model2.fit(x_train,y_train) 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
rf_prediction = rf_model2.predict(x_test) 

In [24]:
print (confusion_matrix (y_test, rf_prediction))

[[ 443   12]
 [   0 2400]]


In [25]:
print (classification_report (y_test, rf_prediction))

              precision    recall  f1-score   support

          no       1.00      0.97      0.99       455
         yes       1.00      1.00      1.00      2400

    accuracy                           1.00      2855
   macro avg       1.00      0.99      0.99      2855
weighted avg       1.00      1.00      1.00      2855



Random Forests is model is beter than Decision Tree model

In [26]:
from sklearn import metrics
print("Accuracy =",format(metrics.accuracy_score(y_test, rf_prediction)))

Accuracy = 0.9957968476357268


In [27]:
## Hyper Parameter Optimization

params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [28]:
from sklearn.model_selection import RandomizedSearchCV
import xgboost

In [29]:
classifier = xgboost.XGBRFClassifier()

In [30]:
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)

In [31]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [32]:
from datetime import datetime
# Here we go
start_time = timer(None) # timing starts from this point for "start_time" variable
random_search.fit(x,y.ravel())
timer(start_time) # timing ends here for "start_time" variable

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:   23.2s finished



 Time taken: 0 hours 0 minutes and 24.78 seconds.


In [33]:
random_search.best_estimator_

XGBRFClassifier(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
                colsample_bytree=0.4, gamma=0.3, learning_rate=0.05,
                max_delta_step=0, max_depth=6, min_child_weight=1, missing=None,
                n_estimators=100, n_jobs=1, nthread=None,
                objective='binary:logistic', random_state=0, reg_alpha=0,
                reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
                subsample=0.8, verbosity=1)

In [34]:
classifier =xgboost.XGBRFClassifier(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
                colsample_bytree=0.4, gamma=0.3, learning_rate=0.05,
                max_delta_step=0, max_depth=6, min_child_weight=1, missing=None,
                n_estimators=100, n_jobs=1, nthread=None,
                objective='binary:logistic', random_state=0, reg_alpha=0,
                reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
                subsample=0.8, verbosity=1)

In [36]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(classifier,x,y.ravel(),cv=10)

In [37]:
score

array([0.9789916 , 0.9842437 , 0.9842437 , 0.99159664, 0.98319328,
       0.9789916 , 0.98107256, 0.98948475, 0.99684543, 0.99894848])

In [38]:
score.mean()

0.9867611713455098